# Credit Risk Resampling Techniques

In [35]:
import warnings
warnings.filterwarnings('ignore')

In [36]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV into DataFrame

In [37]:
# Load the data
file_path = Path('Resources/lending_data.csv')
df = pd.read_csv(file_path)
df.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  
0                5                 1       22800    low_risk  
1                3                 0       13600    low_risk  
2                3                 0       16100    low_risk  
3                5                 1       22700    low_risk  
4                5                 1       23000    low_risk

# Split the Data into Training and Testing

In [42]:
# Create our features
# YOUR CODE HERE
X = df.drop(columns=['loan_status','homeowner'])

# Create our target
y = df['loan_status'] # YOUR CODE HERE

In [39]:
X.describe()

loan_size  interest_rate  borrower_income  debt_to_income  \
count  77536.000000   77536.000000     77536.000000    77536.000000   
mean    9805.562577       7.292333     49221.949804        0.377318   
std     2093.223153       0.889495      8371.635077        0.081519   
min     5000.000000       5.250000     30000.000000        0.000000   
25%     8700.000000       6.825000     44800.000000        0.330357   
50%     9500.000000       7.172000     48100.000000        0.376299   
75%    10400.000000       7.528000     51400.000000        0.416342   
max    23800.000000      13.235000    105200.000000        0.714829   

       num_of_accounts  derogatory_marks    total_debt  
count     77536.000000      77536.000000  77536.000000  
mean          3.826610          0.392308  19221.949804  
std           1.904426          0.582086   8371.635077  
min           0.000000          0.000000      0.000000  
25%           3.000000          0.000000  14800.000000  
50%           4.000000          0.000000  18100.000000  
75%           4.000000          1.000000  21400.000000  
max          16.000000          3.000000  75200.000000

In [43]:
# Check the balance of our target values
y.value_counts()

low_risk     75036
high_risk     2500
Name: loan_status, dtype: int64

In [60]:
# Create X_train, X_test, y_train, y_test
# YOUR CODE HERE
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

In [61]:
# Checking data types for each 
X_train.dtypes

loan_size           float64
interest_rate       float64
borrower_income       int64
debt_to_income      float64
num_of_accounts       int64
derogatory_marks      int64
total_debt            int64
dtype: object

In [62]:
Counter(y_train)

Counter({'low_risk': 56271, 'high_risk': 1881})

In [63]:
X_train.describe()

loan_size  interest_rate  borrower_income  debt_to_income  \
count  58152.000000   58152.000000     58152.000000    58152.000000   
mean    9807.982529       7.293376     49231.752992        0.377465   
std     2093.250476       0.889482      8371.427552        0.081385   
min     5000.000000       5.250000     30000.000000        0.000000   
25%     8700.000000       6.828000     44900.000000        0.331849   
50%     9500.000000       7.172000     48100.000000        0.376299   
75%    10400.000000       7.527000     51400.000000        0.416342   
max    23800.000000      13.235000    105200.000000        0.714829   

       num_of_accounts  derogatory_marks    total_debt  
count     58152.000000      58152.000000  58152.000000  
mean          3.827985          0.392076  19231.752992  
std           1.903875          0.582672   8371.427552  
min           0.000000          0.000000      0.000000  
25%           3.000000          0.000000  14900.000000  
50%           4.000000          0.000000  18100.000000  
75%           4.000000          1.000000  21400.000000  
max          16.000000          3.000000  75200.000000

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [64]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
# YOUR CODE HERE
scaler = StandardScaler()

In [65]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
# YOUR CODE HERE
X_scaler = scaler.fit(X_train)
X_train_scaled = scaler.fit_transform(X_train)
print(X_train_scaled)

[[-0.57708952 -0.56367666 -0.5652314  ... -0.43489843 -0.67289855
  -0.5652314 ]
 [-0.95927354 -0.98302549 -0.98332378 ... -0.96014741 -0.67289855
  -0.98332378]
 [ 0.09173251  0.10413354  0.10371642 ...  0.09035056  1.04334691
   0.10371642]
 ...
 [ 0.18727852  0.19070153  0.18733489 ...  0.09035056  1.04334691
   0.18733489]
 [ 0.61723554  0.61229888  0.61737277 ...  0.61559954  1.04334691
   0.61737277]
 [ 0.37837052  0.3807014   0.37846284 ...  0.61559954  1.04334691
   0.37846284]]


In [66]:
# Scale the training and testing data
# YOUR CODE HERE
X_test_scaled = X_scaler.transform(X_test)
print(X_test_scaled)

[[ 1.33383057  1.32170668  1.32215708 ...  1.14084852  1.04334691
   1.32215708]
 [-0.00381349 -0.00491964 -0.00379305 ...  0.09035056 -0.67289855
  -0.00379305]
 [ 0.52168953  0.53584922  0.5337543  ...  0.61559954  1.04334691
   0.5337543 ]
 ...
 [-0.86372754 -0.86947527 -0.86386881 ... -0.96014741 -0.67289855
  -0.86386881]
 [ 0.80832755  0.79555319  0.79655522 ...  0.61559954  1.04334691
   0.79655522]
 [-0.29045151 -0.30284843 -0.30243047 ... -0.43489843 -0.67289855
  -0.30243047]]


# Simple Logistic Regression

In [67]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [68]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9520479254722232

In [69]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[  563,    56],
       [  102, 18663]], dtype=int64)

In [70]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred)) # ??

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      0.91      0.99      0.88      0.95      0.90       619
   low_risk       1.00      0.99      0.91      1.00      0.95      0.91     18765

avg / total       0.99      0.99      0.91      0.99      0.95      0.91     19384



# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [71]:
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import RandomOverSampler

In [72]:
# Resample the training data with the RandomOversampler
# YOUR CODE HERE
rand_os = RandomOverSampler(random_state=1)
X_resampled, y_resampled = rand_os.fit_resample(X_train, y_train)
# View the count of target classes with Counter
# YOUR CODE HERE
print(sorted(Counter(y_resampled).items()),y_resampled.shape) 

[('high_risk', 56271), ('low_risk', 56271)] (112542,)


In [73]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE
modelz = LogisticRegression(solver='lbfgs', random_state=1)
modelz.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [74]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
y_resampled_pred = modelz.predict(X_test)
balanced_accuracy_score(y_test, y_resampled_pred)

0.9936781215845847

In [75]:
# Display the confusion matrix
# YOUR CODE HERE
y_resampled_pred = modelz.predict(X_test)
confusion_matrix(y_test, y_resampled_pred)

array([[  615,     4],
       [  116, 18649]], dtype=int64)

In [76]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, y_resampled_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.99      0.99      0.91      0.99      0.99       619
   low_risk       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



### SMOTE Oversampling

In [79]:
from imblearn.over_sampling import SMOTE
# Resample the training data with SMOTE
# YOUR CODE HERE
X_resample, y_resample = SMOTE(random_state=1, sampling_strategy=1).fit_resample(X_train, y_train)
# View the count of target classes with Counter
# YOUR CODE HERE
Counter(y_resample)

Counter({'low_risk': 56271, 'high_risk': 56271})

In [81]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE
smote_model = LogisticRegression(solver='lbfgs', random_state=1)
smote_model.fit(X_resample, y_resample)

LogisticRegression(random_state=1)

In [82]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
y_smote_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_smote_pred)

0.9520479254722232

In [83]:
# Display the confusion matrix
# YOUR CODE HERE
confusion_matrix(y_test, y_smote_pred)

array([[  563,    56],
       [  102, 18663]], dtype=int64)

In [84]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, y_smote_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      0.91      0.99      0.88      0.95      0.90       619
   low_risk       1.00      0.99      0.91      1.00      0.95      0.91     18765

avg / total       0.99      0.99      0.91      0.99      0.95      0.91     19384



# Undersampling

In this section, you will test an undersampling algorithm to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [87]:
# Undersample w/ the ClusterCentroids import from imblearn.under_sampling
from imblearn.under_sampling import ClusterCentroids
# Initialize the ClusterCentroids 
clt_cntrds = ClusterCentroids(random_state=1)
# Resample the data using the ClusterCentroids resampler
# YOUR CODE HERE
X_resampled, y_resampled = clt_cntrds.fit_resample(X_train,y_train)
# View the count of target classes with Counter
# YOUR CODE HERE
Counter(y_resampled)

Counter({'high_risk': 1881, 'low_risk': 1881})

In [88]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE
under_model = LogisticRegression(solver='lbfgs', random_state=1)
under_model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [89]:
# Calculate the balanced accuracy score
# YOUR CODE HERE
y_under_pred = under_model.predict(X_test)
balanced_accuracy_score(y_test, y_under_pred)

0.9881037765371978

In [90]:
# Display the confusion matrix
# YOUR CODE HERE
confusion_matrix(y_test, y_under_pred)

array([[  608,    11],
       [  113, 18652]], dtype=int64)

In [91]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, y_under_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.98      0.99      0.91      0.99      0.98       619
   low_risk       1.00      0.99      0.98      1.00      0.99      0.98     18765

avg / total       0.99      0.99      0.98      0.99      0.99      0.98     19384



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [93]:
from imblearn.combine import SMOTEENN

# Initialize the import
smote_enn = SMOTEENN(random_state=1)

In [94]:
# Resample the training data with SMOTEENN
# YOUR CODE HERE
X_resampled, y_resampled = smote_enn.fit_resample(X_train, y_train)
# View the count of target classes with Counter
# YOUR CODE HERE
Counter(y_resampled)

Counter({'high_risk': 55382, 'low_risk': 55945})

In [95]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [96]:
# Calculate the balanced accuracy score
# YOUR CODE HERE
y_smoteenn_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_smoteenn_pred)

0.9935182494822666

In [97]:
# Display the confusion matrix
# YOUR CODE HERE
confusion_matrix(y_test, y_smoteenn_pred)

array([[  615,     4],
       [  122, 18643]], dtype=int64)

In [98]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, y_smoteenn_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.83      0.99      0.99      0.91      0.99      0.99       619
   low_risk       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



# Final Questions

1. Which model had the best balanced accuracy score?

    The model with the best balanced accuracy score is Naive Random Oversampling.The model with the best balanced accuracy score is Naive Random Oversampling.
   

2. Which model had the best recall score?

    The model with the best recall score tied between all models with a score of .99 for each of them.The model with the best recall score tied between all models with a score of .99 for each of them.

3. Which model had the best geometric mean score?

   The model with the best geometric mean score was a tie between Naive RandomOversampling, Undersampling, and Combination Sampling.The model with the best geometric mean score was a tie between Naive RandomOversampling, Undersampling, and Combination Sampling.